name: Deploy Nutrifit (Self-Hosted)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      APP_DIR: /opt/apps/nutrifit
      ENV_FILE: .env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copiar arquivos pro APP_DIR (sem sudo)
        run: |
          mkdir -p "$APP_DIR"
          shopt -s dotglob
          rm -rf "$APP_DIR"/*
          cp -r ./* "$APP_DIR"/
          shopt -u dotglob

      - name: Criar .env
        working-directory: ${{ env.APP_DIR }}
        run: |
          cat > "${ENV_FILE}" <<EOF
          POSTGRES_USER=${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.NUTRIFIT_POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ env.POSTGRES_DB }}
          POSTGRES_PORT=${{ env.POSTGRES_PORT }}
          POSTGRES_HOST=${{ env.POSTGRES_HOST }}
          REDIS_PORT=${{ env.REDIS_PORT }}
          SMTP_APP_PASSWORD=${{ secrets.SMTP_APP_PASSWORD }}
          FRONT_API_URL=${{ env.FRONT_API_URL }}
          FRONT_PORT=${{ env.FRONT_PORT }}
          EOF
          echo "Arquivo .env gerado:"
          sed -n '1,50p' "${ENV_FILE}" | sed 's/POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=***|/; s/SMTP_APP_PASSWORD=.*/SMTP_APP_PASSWORD=***|/'

      - name: Checar Docker Compose
        run: docker compose version

      - name: Subir containers
        working-directory: ${{ env.APP_DIR }}
        run: |
          docker compose --env-file "${ENV_FILE}" up -d --build
          docker compose ps
